
import {
  KpiMetric,
  WorkflowCategory,
  Reviewer,
  ReviewItem,
  PaymentWindowData,
  ContractCategoryItem,
  OperationalAlert,
}  from "@/types";

export const MOCK_OPERATIONAL_ALERTS: OperationalAlert[] = [
  {
    id: "alt-1",
    title: "Workflow Bottleneck in Stage 2",
    description: "58 items queued at 'Ready for Review' (+34% SLA delay threshold)",
    severity: "high",
    category: "workflow",
    timestamp: "10 mins ago",
    actionText: "Inspect Stage",
    actionKey: "ready-for-review",
  },
  {
    id: "alt-2",
    title: "Unassigned Review Items Warning",
    description: "5 urgent compliance items waiting for reviewer assignment",
    severity: "high",
    category: "review",
    timestamp: "25 mins ago",
    actionText: "Reassign Workload",
    actionKey: "reassign-unassigned",
  },
  {
    id: "alt-3",
    title: "Reviewer Capacity Overload",
    description: "Rachel B. is at 100% capacity limit (20 active items)",
    severity: "medium",
    category: "review",
    timestamp: "1 hour ago",
    actionText: "Balance Capacity",
    actionKey: "rebalance-rachel",
  },
  {
    id: "alt-4",
    title: "Payment Processing Exception",
    description: "3 pending disbursements totaling $820K require secondary dual-signoff",
    severity: "info",
    category: "payment",
    timestamp: "2 hours ago",
    actionText: "View Payments",
    actionKey: "view-payments",
  },
];

export const MOCK_KPIS: KpiMetric[] = [
  {
    id: "kpi-pay-elements",
    title: "Total Pay Elements",
    value: "1,284",
    change: "+4.2%",
    changeType: "positive",
    subtitle: "Active processed records",
    status: "sky",
    sparklineData: [45, 52, 48, 60, 58, 65, 72, 80],
  },
  {
    id: "kpi-compliance",
    title: "In Compliance",
    value: "1,197",
    change: "93.2%",
    changeType: "positive",
    subtitle: "Passes automated rules",
    status: "emerald",
    sparklineData: [90, 92, 91, 93, 92, 94, 93, 95],
  },
  {
    id: "kpi-review-needed",
    title: "Needing Review",
    value: "87",
    change: "+12 items",
    changeType: "negative",
    subtitle: "58 ready, 32 in review",
    status: "rose",
    sparklineData: [40, 45, 50, 62, 58, 70, 82, 87],
  },
  {
    id: "kpi-monitoring",
    title: "Monitoring Volume",
    value: "$4.2M",
    change: "+8.5%",
    changeType: "positive",
    subtitle: "Active pipeline value",
    status: "amber",
    sparklineData: [3.1, 3.4, 3.2, 3.8, 4.0, 4.1, 4.2],
  },
  {
    id: "kpi-captured",
    title: "Captured Value",
    value: "$412K",
    change: "+15.3%",
    changeType: "positive",
    subtitle: "Verified & settled",
    status: "emerald",
    sparklineData: [280, 310, 340, 360, 380, 400, 412],
  },
];

export const MOCK_WORKFLOW_CATEGORIES: WorkflowCategory[] = [
  {
    id: "wf-ingestion",
    categoryName: "Ingestion",
    totalCount: 53,
    stages: [
      { id: "s-1", name: "Uploading", count: 9, avgTimeHours: 0.4, status: "normal" },
      { id: "s-2", name: "Queued", count: 10, avgTimeHours: 0.8, status: "normal" },
      { id: "s-3", name: "Extract Data", count: 34, avgTimeHours: 2.1, status: "normal" },
    ],
  },
  {
    id: "wf-compliance",
    categoryName: "Compliance & Rules",
    totalCount: 87,
    stages: [
      { id: "s-4", name: "Mapping Relationships", count: 66, avgTimeHours: 3.5, status: "normal" },
      { id: "s-5", name: "Compliance Rules", count: 21, avgTimeHours: 1.8, status: "normal" },
    ],
  },
  {
    id: "wf-review",
    categoryName: "Review Pipeline",
    totalCount: 130,
    stages: [
      { id: "s-6", name: "Ready for Review", count: 58, avgTimeHours: 14.2, status: "bottleneck" },
      { id: "s-7", name: "In Review", count: 32, avgTimeHours: 6.8, status: "warning" },
      { id: "s-8", name: "Reviewed", count: 40, avgTimeHours: 2.5, status: "normal" },
    ],
  },
  {
    id: "wf-monitoring",
    categoryName: "Monitoring",
    totalCount: 116,
    stages: [
      { id: "s-9", name: "Vendor Assignment", count: 18, avgTimeHours: 1.2, status: "normal" },
      { id: "s-10", name: "Active", count: 98, avgTimeHours: 0.5, status: "normal" },
    ],
  },
];

export const MOCK_REVIEWERS: Reviewer[] = [
  {
    id: "rev-1",
    name: "Sarah M.",
    role: "Senior Compliance Specialist",
    avatar: "SM",
    assignedCount: 14,
    capacityLimit: 20,
    status: "optimal",
  },
  {
    id: "rev-2",
    name: "James T.",
    role: "Legal Analyst",
    avatar: "JT",
    assignedCount: 11,
    capacityLimit: 20,
    status: "optimal",
  },
  {
    id: "rev-3",
    name: "Priya K.",
    role: "Medical Director Auditor",
    avatar: "PK",
    assignedCount: 17,
    capacityLimit: 20,
    status: "high",
  },
  {
    id: "rev-4",
    name: "David L.",
    role: "Operations Specialist",
    avatar: "DL",
    assignedCount: 6,
    capacityLimit: 20,
    status: "optimal",
  },
  {
    id: "rev-5",
    name: "Rachel B.",
    role: "Lead Auditor",
    avatar: "RB",
    assignedCount: 20,
    capacityLimit: 20,
    status: "overloaded",
  },
  {
    id: "rev-6",
    name: "Omar F.",
    role: "Contract Specialist",
    avatar: "OF",
    assignedCount: 12,
    capacityLimit: 20,
    status: "optimal",
  },
  {
    id: "rev-7",
    name: "Lena V.",
    role: "Finance Manager",
    avatar: "LV",
    assignedCount: 19,
    capacityLimit: 20,
    status: "high",
  },
  {
    id: "rev-unassigned",
    name: "Unassigned Queue",
    role: "Awaiting Assignment",
    avatar: "??",
    assignedCount: 5,
    capacityLimit: 0,
    status: "unassigned",
  },
];

export const MOCK_REVIEW_ITEMS: ReviewItem[] = [
  {
    id: "rev-itm-101",
    applicationId: "APP-8921",
    title: "Locum Tenens Emergency On-Call Addendum",
    vendorName: "St. Jude Health Group",
    department: "Clinical",
    stage: "Ready for Review",
    status: "Ready for Review",
    priority: "High",
    assignedReviewerId: "rev-unassigned",
    assignedReviewerName: "Unassigned Queue",
    ageDays: 4,
    dueDate: "2026-09-28",
    contractValue: 299000,
  },
  {
    id: "rev-itm-102",
    applicationId: "APP-8922",
    title: "Annual Medical Director Services Contract",
    vendorName: "Apex Surgical Partners",
    department: "Clinical",
    stage: "Ready for Review",
    status: "Ready for Review",
    priority: "High",
    assignedReviewerId: "rev-unassigned",
    assignedReviewerName: "Unassigned Queue",
    ageDays: 3,
    dueDate: "2026-09-29",
    contractValue: 412000,
  },
  {
    id: "rev-itm-103",
    applicationId: "APP-8923",
    title: "Call Coverage Stipend Amendment",
    vendorName: "Metro Radiology Associates",
    department: "Finance",
    stage: "In Review",
    status: "In Review",
    priority: "High",
    assignedReviewerId: "rev-5",
    assignedReviewerName: "Rachel B.",
    ageDays: 5,
    dueDate: "2026-09-27",
    contractValue: 634000,
  },
  {
    id: "rev-itm-104",
    applicationId: "APP-8924",
    title: "Base Compensation Tier Alignment 2026",
    vendorName: "Valley Care System",
    department: "Legal",
    stage: "In Review",
    status: "In Review",
    priority: "Medium",
    assignedReviewerId: "rev-3",
    assignedReviewerName: "Priya K.",
    ageDays: 2,
    dueDate: "2026-09-30",
    contractValue: 1840000,
  },
  {
    id: "rev-itm-105",
    applicationId: "APP-8925",
    title: "Specialty Bonus Structure Agreement",
    vendorName: "Orthopedic Specialists Network",
    department: "Clinical",
    stage: "Ready for Review",
    status: "Ready for Review",
    priority: "Medium",
    assignedReviewerId: "rev-unassigned",
    assignedReviewerName: "Unassigned Queue",
    ageDays: 1,
    dueDate: "2026-10-01",
    contractValue: 187000,
  },
  {
    id: "rev-itm-106",
    applicationId: "APP-8926",
    title: "Vendor Relationship Data Mapping",
    vendorName: "Horizon Health Solutions",
    department: "Operations",
    stage: "Ready for Review",
    status: "Ready for Review",
    priority: "Low",
    assignedReviewerId: "rev-1",
    assignedReviewerName: "Sarah M.",
    ageDays: 6,
    dueDate: "2026-09-26",
    contractValue: 295000,
  },
  {
    id: "rev-itm-107",
    applicationId: "APP-8927",
    title: "Anesthesia On-Call Coverage Schedule",
    vendorName: "Summit Healthcare",
    department: "Clinical",
    stage: "In Review",
    status: "In Review",
    priority: "High",
    assignedReviewerId: "rev-7",
    assignedReviewerName: "Lena V.",
    ageDays: 2,
    dueDate: "2026-09-28",
    contractValue: 145000,
  },
  {
    id: "rev-itm-108",
    applicationId: "APP-8928",
    title: "Cardiology Department Directorship",
    vendorName: "CardioCare Institute",
    department: "Clinical",
    stage: "Reviewed",
    status: "Reviewed",
    priority: "Medium",
    assignedReviewerId: "rev-2",
    assignedReviewerName: "James T.",
    ageDays: 7,
    dueDate: "2026-09-25",
    contractValue: 310000,
  },
];

export const MOCK_PAYMENTS_DATA: PaymentWindowData[] = [
  {
    period: "7 Days",
    approved: 1900000,
    pending: 820000,
    failed: 45000,
    approvedFormatted: "$1.9M",
    pendingFormatted: "$820K",
  },
  {
    period: "14 Days",
    approved: 2000000,
    pending: 1200000,
    failed: 32000,
    approvedFormatted: "$2.0M",
    pendingFormatted: "$1.2M",
  },
  {
    period: "30 Days",
    approved: 3400000,
    pending: 1600000,
    failed: 60000,
    approvedFormatted: "$3.4M",
    pendingFormatted: "$1.6M",
  },
  {
    period: "60+ Days",
    approved: 4200000,
    pending: 2100000,
    failed: 95000,
    approvedFormatted: "$4.2M",
    pendingFormatted: "$2.1M",
  },
];

export const MOCK_CONTRACT_CATEGORIES: ContractCategoryItem[] = [
  {
    id: "cat-1",
    name: "Base Compensation",
    amount: 1840000,
    amountFormatted: "$1.84M",
    percentageOfTotal: 50.1,
    color: "#4F46E5", // Indigo
    status: "active",
  },
  {
    id: "cat-2",
    name: "Call Coverage Rate",
    amount: 634000,
    amountFormatted: "$634K",
    percentageOfTotal: 17.3,
    color: "#06B6D4", // Cyan
    status: "active",
  },
  {
    id: "cat-3",
    name: "Med. Director Stipend",
    amount: 412000,
    amountFormatted: "$412K",
    percentageOfTotal: 11.2,
    color: "#10B981", // Emerald
    status: "active",
  },
  {
    id: "cat-4",
    name: "Locum Tenens Daily",
    amount: 299000,
    amountFormatted: "$299K",
    percentageOfTotal: 8.1,
    color: "#F59E0B", // Amber
    status: "review",
  },
  {
    id: "cat-5",
    name: "Bonus Structure",
    amount: 187000,
    amountFormatted: "$187K",
    percentageOfTotal: 5.1,
    color: "#8B5CF6", // Purple
    status: "active",
  },
  {
    id: "cat-6",
    name: "Other Contingencies",
    amount: 295000,
    amountFormatted: "$295K",
    percentageOfTotal: 8.0,
    color: "#64748B", // Slate
    status: "pending",
  },
];

export const TOTAL_CONTRACT_VALUE_FORMATTED = "$3.67M";
export const TOTAL_CONTRACT_VALUE_NUMERIC = 3667000;
